apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: noop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: noop-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: noop-service
      name: noop-service
    spec:
      containers:
      - env:
        image: ness2u/noop:latest
        imagePullPolicy: Always
        name: noop-service
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
